# Generated by Django 3.2 on 2021-04-17 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_institution', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='matter_id',
            new_name='matter',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='enrollment_id',
            new_name='enrollment',
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_institution.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(to='education_institution.Group'),
        ),
    ]
