# Generated by Django 3.2 on 2021-04-18 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('serial', models.CharField(blank=True, max_length=150, null=True)),
                ('inventory', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('A', 'Activo'), ('N', 'Anulado'), ('R', 'Reparación'), ('P', 'Prestado'), ('B', 'Baja')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='AssetField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sectional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('pattern_inventory', models.CharField(blank=True, max_length=30, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Third',
            fields=[
                ('identification', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fixed_assets.documenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fixed_assets.building')),
                ('flat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='fixed_assets.flat')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='fixed_assets.space')),
            ],
        ),
        migrations.CreateModel(
            name='TransferField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fixed_assets.assetfield')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fixed_assets.transfer')),
            ],
        ),
        migrations.CreateModel(
            name='TransferDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('value', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fixed_assets.asset')),
                ('asset_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='fixed_assets.assetfield')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fixed_assets.transfer')),
            ],
        ),
        migrations.CreateModel(
            name='DropDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fixed_assets.asset')),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fixed_assets.drop')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='sectional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fixed_assets.sectional'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fixed_assets.assettype'),
        ),
        migrations.AddField(
            model_name='asset',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='fixed_assets.supplier'),
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('third_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fixed_assets.third')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='fixed_assets.costcenter')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='fixed_assets.position')),
                ('sectional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='fixed_assets.sectional')),
            ],
            bases=('fixed_assets.third',),
        ),
    ]
