# Generated by Django 3.2 on 2021-04-10 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Third',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('third_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='EducationInstitution.third')),
                ('code', models.IntegerField(primary_key=True, serialize=False)),
            ],
            bases=('EducationInstitution.third',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('third_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EducationInstitution.third')),
            ],
            bases=('EducationInstitution.third',),
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationInstitution.matter')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationInstitution.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('matter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationInstitution.matter')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationInstitution.student')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationInstitution.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationInstitution.matter')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationInstitution.student')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationInstitution.teacher')),
            ],
        ),
    ]
